name: Quality Checks

on:
  workflow_call:

jobs:
  check-license-header:
    name: License Header Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Licensor
        uses: nicebots-xyz/licensor/.github/actions/setup-licensor@20ff71ae4c0ca9874893c11c7c2cbdb9d22e179e # v0.1.0
        with:
          version: v0.1.0
      - name: Check Header Compliance
        run: licensor check * --ignore ".*" --ignore build

  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [format, lint, basedpyright]
        include:
          - check: format
            name: "Format Check"
            command: "pdm run format:check"
          - check: lint
            name: "Lint Check"
            command: "pdm run lint"
          - check: basedpyright
            name: "Type Check"
            command: "pdm run typecheck"

    name: ${{ matrix.name }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: "Setup PDM"
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4

      - name: "Install Dependencies"
        run: "pdm install"

      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}